# Keybind
set-option -g prefix C-t
bind-key C-t send-prefix
unbind-key C-b

bind-key C-c new-window
bind-key C-n next-window
bind-key C-p previous-window
bind-key C-o select-pane -t :.+
bind-key C-d detach
bind-key C-r copy-mode \; command-prompt -i -I "#{pane_search_string}" -T search -p "(search up)" { send-keys -X search-backward-incremental "%%" }
# stay copy-mode after dragging mouse
unbind-key -T copy-mode MouseDragEnd1Pane
bind-key -T copy-mode MouseDown1Pane select-pane \; send-keys -X clear-selection
# stay copy-mode after copy (use C-w to copy & exit copy-mode)
bind-key -T copy-mode M-w send-keys -X copy-pipe

set-option -g history-limit 90000

# color for copy mode selection
set-window-option -g mode-style fg=black,bg=blue

# status bar
set -g status-bg colour153
set -g window-status-current-style 'bold'
# don't need * (current window), - (last window), and ~ (silence)
set -g window-status-current-format '▶#I:#W#{?window_zoomed_flag,(Z),}#{?window_bell_flag,(!!),}'
set -g window-status-format         '#I:#W#{?window_zoomed_flag,(Z),}#{?window_bell_flag,(!!),}'
# Remove date/time from status-right; expand length to 100 and trim pane_title to 98 to always show closing quote
set -g status-right-length 100
set -g status-right '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=98:pane_title}"'

# terminal title
set-option -g set-titles on
set-option -g set-titles-string "#{active_window_index}: #{pane_title} (#{window_name})"

# mouse
set-option -g mouse on

# TERM
set -g default-terminal "xterm-256color"
